server:
  port: 8080

spring:
  config:
    import: "optional:configserver:"
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
      discovery:
        locator:
          enabled: true   # Enables dynamic routing using Eureka service names

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
